[package]
name = "CSC110-111-Lean-Seminars"
version = "0.1"
lean_version = "leanprover-community/lean:3.48.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "eb9738966c73ad83d7fcdb817ab74262f9e4e3df"}
